Add live page link and sticky navigation to README file
DevaWinner/my-portfolio pull request #6
Opened 2023-05-08 13:01 UTC by DevaWinner

This pull request adds functionality to the page deployment branch. The README file has been updated to include a live page link, allowing users to easily access the deployed version of the site. Additionally, the navigation bar has been made sticky, which ensures that it stays visible at all times, even when the user scrolls down the page. These updates improve the user experience and make it easier for users to access and navigate the deployed version of the site.

2023-05-08 13:33 UTC, skyv26 requested changes
## Hi @DevaWinner, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/3o7aCPbznb29hgOgG4/giphy.gif)

## Highlights
- Correct `GitHub` flow ✅ 
- Linters are green ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-08 13:33 UTC, skyv26 commented on README.md
- [ ] Kindly remove the `placeholders` or unnecessary `comments` from your `README` file, because these kinds of comment make your `README` looks unprofessional. These kinds of comments are actually meant for developers only to help them to create great *documentation* for the project to make a user's life easier. Please take a look at the below image. 

![Screenshot from 2023-05-08 18-50-50](https://user-images.githubusercontent.com/66476329/236836647-7b55d53d-21dd-4ac5-bdf6-dfcf6d3af02e.png)

- [ ] Please use the *Microverse* README `template` properly. You used the right template but the problem is you removed some important sections of your `README` file which we can consider as the *Recipe of the food*, I mean help the user to navigate and use your project properly without any issues.

<table>
<tr>
<th>Example README</th>
<th>Your README</th>
</tr>
<tr>
<td>

![Screenshot from 2023-05-08 18-55-11](https://user-images.githubusercontent.com/66476329/236837616-fb882de3-1281-4223-9d2a-607a3b73cc16.png)

</td>
<td>

![Screenshot from 2023-05-08 18-51-32](https://user-images.githubusercontent.com/66476329/236837646-7f55bd7a-7d46-4160-b4c1-5bcd82ecb77c.png)

</td>
</tr>
</table>

2023-05-09 07:39 UTC, DevaWinner commented on README.md
Hello @skyv26, I have resolved the first suggestion by removing the highlighted comments from the README file. 

For the second comment, you said I used the suitable template but I removed some important sections of the README file, where was the section in the original file? I can't find it anywhere to copy it back. 

Earlier, we were asked to remove parts of the README that weren't applicable to our current project.

2023-05-09 07:56 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/7SyGkO0kQWCfnUC47Y/giphy.gif)


# Hi @DevaWinner 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Correct use of GitHub Flow ✔
- All linter checks are passing ✔

 ## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 07:56 UTC, AbelG101 commented on README.md
- [ ] As suggested by the previous reviewer please make sure to remove any section description from your readme file 👇
  ![image](https://user-images.githubusercontent.com/104968236/237030829-cb56ec23-2351-4556-964a-8cd4bcfe38a5.png)
- [ ] Once again as mentioned previously you don't seem to have the "Install", "Usage" & "Run Linters" sections in your readme. These sections shouldn't be removed as they guide the user on how to install and use your project and are applicable to any repo. ✔
- Pelase revisit the [Microverse README here](https://github.com/microverseinc/readme-template/blob/master/README.md)

2023-05-09 20:27 UTC, DevaWinner commented on README.md
@skyv26 Thank you for the detailed explanation. I appreciate the feedback.

2023-05-09 20:31 UTC, taldr27 approved these changes
# Status: Approved! 🟢 
Hi @DevaWinner, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉

![congrats](https://media.giphy.com/media/3oEjI5VtIhHvK37WYo/giphy.gif)

## Highlights 🎉
✅ Professional and customized README. 🙌
✅ README includes a working live link. 🎯
✅ Successfully deployed using GitHub Pages. 🤓
✅ Live page is fully functional. 👍


-----
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-05-09 20:37 UTC, merged