Implement Popup Window Functionality
DevaWinner/my-portfolio pull request #8
Opened 2023-05-19 14:49 UTC by DevaWinner

Description:
This pull request adds the functionality for a popup window to enhance user interactions on the website. The popup window allows for displaying additional information, alerts, or user prompts without disrupting the main page flow.

Changes Made:

Created a new JavaScript module for handling the popup window functionality.
Implemented the ability to open and close the popup window.
Added CSS styles to customize the appearance and position of the popup window.
Integrated event listeners to trigger the popup window on specific user interactions.

2023-05-19 16:27 UTC, Ibizugbe requested changes
Hi @DevaWinner 👋👋, 

![tryagain](https://github.com/DevaWinner/my-portfolio/assets/64643995/04f73dab-67e3-4711-b66b-368b242c5085)


Good job so far!👍.
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅

- [x] Linters are properly setup and they are passing👍.
- [x] Project section and popup are generayed dynamically👍.
- [x] Popup functionalities (open and close) works properly👍.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] Your headline section looks different from the design, kindly take note of it and make the necessary adjustments as it is a good display of professionalism that your project matches the design👍.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-19 16:27 UTC, Ibizugbe commented on script.js
> +  button.innerHTML = itemContent.buttonText;
Nice job implementing the functionalities of the popup😉. Let's make a slight change to the mobile section so the popup matches the design😉.

Your project
<img width="280" alt="image" src="https://github.com/DevaWinner/my-portfolio/assets/64643995/4107bd09-c2ba-43fb-9e67-161f740c5d03">

design
<img width="297" alt="image" src="https://github.com/DevaWinner/my-portfolio/assets/64643995/cd830dfc-9465-4b5b-9b69-777eb4ceca7a">

Kindly take note of the spacings and border roundness of the badge, and the font properties and make the necessary changes👍.

2023-05-19 17:01 UTC, DevaWinner commented on script.js
> +  button.innerHTML = itemContent.buttonText;
Thank you for taking the time to review my Pull Request. I have resolved this changes.

2023-05-19 17:52 UTC, Yerimah requested changes
# STATUS: REQUIRED CHANGES 🔴 

Hi @DevaWinner, 👋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter error 👍 
- Descriptive PR summary and title 👍 
- Popup feature is functional 👍 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-19 17:52 UTC, Yerimah commented on style.css
>  .card div > h1 {
- [ ]  Hey @DevaWinner, you have done well implementing the feature for this task but there are some mandatory requirements I would suggest that you fulfill as part of the general requirements for this project.

- Kindly fix the styling on the cards in your work section. Use your chosen Figma template as a guide and ensure that your design looks exactly like the Original template this will greatly improve the UI of your portfolio and increase your chances of securing a job. 
- Add the required margins on your buttons.

> Your Design
<img width="947" alt="Screenshot 2023-05-19 at 18 10 29" src="https://github.com/DevaWinner/my-portfolio/assets/71140133/eb4e02fc-07fb-4686-b64b-972a37462e8e">

> Figma design
<img width="689" alt="Screenshot 2023-05-19 at 18 10 00" src="https://github.com/DevaWinner/my-portfolio/assets/71140133/b74f66de-8b50-4458-bf93-5bebf371f8a2">

2023-05-19 17:52 UTC, Yerimah commented on style.css
- [ ] Kindly adjust and improve the look of the Language section


> Your design
<img width="909" alt="Screenshot 2023-05-19 at 18 11 53" src="https://github.com/DevaWinner/my-portfolio/assets/71140133/6881cbfa-5e24-4a2e-991b-be02f9a2e89b">


> Figma Design
<img width="670" alt="Screenshot 2023-05-19 at 18 11 36" src="https://github.com/DevaWinner/my-portfolio/assets/71140133/a4e38c13-3a1a-495b-85f7-64816f115553">
 

- On your contact page, fix the form width and align the text on the left to the original design


> Your design
<img width="947" alt="Screenshot 2023-05-19 at 18 13 17" src="https://github.com/DevaWinner/my-portfolio/assets/71140133/f21aae83-4e3e-4968-9268-d813c8faa729">


> Figma design
<img width="686" alt="Screenshot 2023-05-19 at 18 50 31" src="https://github.com/DevaWinner/my-portfolio/assets/71140133/64fc3fe9-97a7-4e9c-86af-229ace39bb73">

2023-05-19 18:21 UTC, DevaWinner commented on style.css
Thank you for taking the time to review my project. Please, kindly crosscheck this again. I don't know how you managed to get this. The first reviewer didn't see my job as this, I've also asked my partner to pull and check my work, it's normal still. Please kindly confirm this.

I think you might be using a wrong browser width or something.

2023-05-20 08:00 UTC, DevaWinner commented on style.css
>  .card div > h1 {
Hello, I would like to add that this screenshot doesn't look like my design on the desktop view. Can you please crosscheck this? This is a shot of my design on desktop view.

![Screenshot from 2023-05-20 08-55-00](https://github.com/DevaWinner/my-portfolio/assets/122822848/6ff1ddb4-c4fa-4748-b201-b2b9e5f555cc)

2023-05-20 08:00 UTC, DevaWinner commented on style.css
With these too.

![Screenshot from 2023-05-20 08-55-00](https://github.com/DevaWinner/my-portfolio/assets/122822848/aa6266e1-64fd-4184-b5f6-3ee35ff3febd)
![Screenshot from 2023-05-20 08-55-22](https://github.com/DevaWinner/my-portfolio/assets/122822848/0f474b61-76fe-43c8-9ce2-94993ffccfdf)

2023-05-20 08:01 UTC, DevaWinner commented on style.css
![Screenshot from 2023-05-20 08-55-13](https://github.com/DevaWinner/my-portfolio/assets/122822848/5b03da91-940a-47ad-bfe8-805ff49f32d7)

2023-05-20 08:10 UTC, DevaWinner commented on style.css
>  .card div > h1 {
Please, The middle card being taller is a hover effect. I took the shot while hovering on it.

2023-05-20 08:19 UTC, frank1738 approved these changes
Hi @DevaWinner , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-20 08:21 UTC, merged